### PR TITLE
 improved incoming call cancellation & refactored to use deferred events.

### LINKED ISSUE #376: gammu 1.38.6 - HangupCalls and RunOnIncomingCall not working
Hello,

With gammu 1.38.6 we're trying to use HangupCalls and RunOnIncomingCall.
Unfortunately gammu does nothing when phone is ringing:

```
Wed 2017/12/13 12:26:36 gammu-smsd[1809]: gammu: Leaving GSM_GetSMSStatus
Wed 2017/12/13 12:26:40 gammu-smsd[1809]: Execute SQL: SELECT "ID", "InsertIntoDB", "SendingDateTime", "SenderID" FROM outbox WHERE "SendingDateTime" < now() AND "SendingTimeOut" < now() AND "SendBefore" >= localtime AND "SendAfter" <= localtime AND ( "SenderID" is NULL OR "SenderID" = '' OR "SenderID" = 'smseagle1' ) ORDER BY "Priority" DESC, "InsertIntoDB" ASC LIMIT 1
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: Entering GSM_GetSecurityStatus
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: Getting security code status
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: SENDING frame type 0x00/length 0x09/9
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: 41A|54T|2B+|43C|50P|49I|4EN|3F?|0D                              AT+CPIN?.
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: 1 "RING"
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: Checking line: RING
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: AT reply state: 4
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: RECEIVED frame type 0x00/length 0x06/6
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: 52R|49I|4EN|47G|0D |0A                                          RING..
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: Incoming call info
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: 1 "RING"
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: Checking line: RING
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: AT reply state: 4
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: RECEIVED frame type 0x00/length 0x06/6
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: 52R|49I|4EN|47G|0D |0A                                          RING..
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: Incoming call info
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: 1 "RING"
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: Checking line: RING
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: AT reply state: 4
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: RECEIVED frame type 0x00/length 0x06/6
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: 52R|49I|4EN|47G|0D |0A                                          RING..
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: Incoming call info
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: 1 "AT+CPIN?"
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: 2 "+CPIN: READY"
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: 3 "OK"
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: Checking line: OK
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: AT reply state: 1
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: RECEIVED frame type 0x00/length 0x1F/31
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: 41A|54T|2B+|43C|50P|49I|4EN|3F?|0D |0D |0A |2B+|43C|50P|49I|4EN AT+CPIN?...+CPIN
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: 3A:|20 |52R|45E|41A|44D|59Y|0D |0A |0D |0A |4FO|4BK|0D |0A      : READY....OK..
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: Parsing +CPIN: READY with +CPIN: @r
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: Grabbed string from reply: "READY" (parsed 5 bytes)
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: Parsed raw string "READY"
Wed 2017/12/13 12:26:50 gammu-smsd[1809]: gammu: Security status received - nothing to enter
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: Leaving GSM_GetSecurityStatus
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: Entering GSM_GetSMSStatus
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: Getting SIM SMS status
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: SENDING frame type 0x00/length 0x12/18
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: 41A|54T|2B+|43C|50P|4DM|53S|3D=|22"|53S|4DM|22"|2C,|22"|53S|4DM AT+CPMS="SM","SM
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: 22"|0D                                                          ".
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: 1 "AT+CPMS="SM","SM""
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: 2 "+CPMS: 0,20,0,20,0,20"
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: 3 "OK"
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: Checking line: OK
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: AT reply state: 1
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: RECEIVED frame type 0x00/length 0x31/49
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: 41A|54T|2B+|43C|50P|4DM|53S|3D=|22"|53S|4DM|22"|2C,|22"|53S|4DM AT+CPMS="SM","SM
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: 22"|0D |0D |0A |2B+|43C|50P|4DM|53S|3A:|20 |300|2C,|322|300|2C, "...+CPMS: 0,20,
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: 300|2C,|322|300|2C,|300|2C,|322|300|0D |0A |0D |0A |4FO|4BK|0D  0,20,0,20....OK.
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: 0A                                                              .
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: SMS status received
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: Parsing +CPMS: 0,20,0,20,0,20 with +CPMS: @i, @i, @0
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: Parsed int 0
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: Parsed int 20
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: Used : 0
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: Size : 20
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: Getting phone SMS status
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: SENDING frame type 0x00/length 0x12/18
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: 41A|54T|2B+|43C|50P|4DM|53S|3D=|22"|4DM|45E|22"|2C,|22"|4DM|45E AT+CPMS="ME","ME
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: 22"|0D                                                          ".
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: 1 "AT+CPMS="ME","ME""
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: 2 "+CPMS: "ME",0,100,"ME",0,100,"ME",0,100"
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: 3 "OK"
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: Checking line: OK
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: AT reply state: 1
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: RECEIVED frame type 0x00/length 0x43/67
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: 41A|54T|2B+|43C|50P|4DM|53S|3D=|22"|4DM|45E|22"|2C,|22"|4DM|45E AT+CPMS="ME","ME
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: 22"|0D |0D |0A |2B+|43C|50P|4DM|53S|3A:|20 |22"|4DM|45E|22"|2C, "...+CPMS: "ME",
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: 300|2C,|311|300|300|2C,|22"|4DM|45E|22"|2C,|300|2C,|311|300|300 0,100,"ME",0,100
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: 2C,|22"|4DM|45E|22"|2C,|300|2C,|311|300|300|0D |0A |0D |0A |4FO ,"ME",0,100....O
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: 4BK|0D |0A                                                      K..
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: SMS status received
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: Parsing +CPMS: "ME",0,100,"ME",0,100,"ME",0,100 with +CPMS: @i, @i, @0
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: Parsing +CPMS: "ME",0,100,"ME",0,100,"ME",0,100 with +CPMS: @s, @i, @i, @0
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: Grabbed string from reply: "ME" (parsed 4 bytes)
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: Parsed generic string "ME"
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: Generic string decoded as "ME"
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: Parsed int 0
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: Parsed int 100
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: Used : 0
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: Size : 100
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: gammu: Leaving GSM_GetSMSStatus
Wed 2017/12/13 12:26:51 gammu-smsd[1809]: Execute SQL: SELECT "ID", "InsertIntoDB", "SendingDateTime", "SenderID" FROM outbox WHERE "SendingDateTime" < now() AND "SendingTimeOut" < now() AND "SendBefore" >= localtime AND "SendAfter" <= localtime AND ( "SenderID" is NULL OR "SenderID" = '' OR "SenderID" = 'smseagle1' ) ORDER BY "Priority" DESC, "InsertIntoDB" ASC LIMIT 1
Wed 2017/12/13 12:27:00 gammu-smsd[1809]: Execute SQL: SELECT "ID", "InsertIntoDB", "SendingDateTime", "SenderID" FROM outbox WHERE "SendingDateTime" < now() AND "SendingTimeOut" < now() AND "SendBefore" >= localtime AND "SendAfter" <= localtime AND ( "SenderID" is NULL OR "SenderID" = '' OR "SenderID" = 'smseagle1' ) ORDER BY "Priority" DESC, "InsertIntoDB" ASC LIMIT 1
Wed 2017/12/13 12:27:05 gammu-smsd[1809]: gammu: Entering GSM_GetSecurityStatus
Wed 2017/12/13 12:27:05 gammu-smsd[1809]: gammu: Getting security code status
Wed 2017/12/13 12:27:05 gammu-smsd[1809]: gammu: SENDING frame type 0x00/length 0x09/9
Wed 2017/12/13 12:27:05 gammu-smsd[1809]: gammu: 41A|54T|2B+|43C|50P|49I|4EN|3F?|0D                              AT+CPIN?.
Wed 2017/12/13 12:27:05 gammu-smsd[1809]: gammu: 1 "AT+CPIN?"
Wed 2017/12/13 12:27:05 gammu-smsd[1809]: gammu: 2 "+CPIN: READY"
Wed 2017/12/13 12:27:05 gammu-smsd[1809]: gammu: 3 "OK"
Wed 2017/12/13 12:27:05 gammu-smsd[1809]: gammu: Checking line: OK
Wed 2017/12/13 12:27:05 gammu-smsd[1809]: gammu: AT reply state: 1
Wed 2017/12/13 12:27:05 gammu-smsd[1809]: gammu: RECEIVED frame type 0x00/length 0x1F/31
Wed 2017/12/13 12:27:05 gammu-smsd[1809]: gammu: 41A|54T|2B+|43C|50P|49I|4EN|3F?|0D |0D |0A |2B+|43C|50P|49I|4EN AT+CPIN?...+CPIN
Wed 2017/12/13 12:27:05 gammu-smsd[1809]: gammu: 3A:|20 |52R|45E|41A|44D|59Y|0D |0A |0D |0A |4FO|4BK|0D |0A      : READY....OK..
Wed 2017/12/13 12:27:05 gammu-smsd[1809]: gammu: Parsing +CPIN: READY with +CPIN: @r
Wed 2017/12/13 12:27:05 gammu-smsd[1809]: gammu: Grabbed string from reply: "READY" (parsed 5 bytes)
Wed 2017/12/13 12:27:05 gammu-smsd[1809]: gammu: Parsed raw string "READY"
Wed 2017/12/13 12:27:05 gammu-smsd[1809]: gammu: Security status received - nothing to enter
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: Leaving GSM_GetSecurityStatus
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: Entering GSM_GetSMSStatus
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: Getting SIM SMS status
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: SENDING frame type 0x00/length 0x12/18
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: 41A|54T|2B+|43C|50P|4DM|53S|3D=|22"|53S|4DM|22"|2C,|22"|53S|4DM AT+CPMS="SM","SM
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: 22"|0D                                                          ".
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: 1 "AT+CPMS="SM","SM""
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: 2 "+CPMS: 0,20,0,20,0,20"
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: 3 "OK"
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: Checking line: OK
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: AT reply state: 1
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: RECEIVED frame type 0x00/length 0x31/49
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: 41A|54T|2B+|43C|50P|4DM|53S|3D=|22"|53S|4DM|22"|2C,|22"|53S|4DM AT+CPMS="SM","SM
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: 22"|0D |0D |0A |2B+|43C|50P|4DM|53S|3A:|20 |300|2C,|322|300|2C, "...+CPMS: 0,20,
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: 300|2C,|322|300|2C,|300|2C,|322|300|0D |0A |0D |0A |4FO|4BK|0D  0,20,0,20....OK.
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: 0A                                                              .
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: SMS status received
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: Parsing +CPMS: 0,20,0,20,0,20 with +CPMS: @i, @i, @0
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: Parsed int 0
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: Parsed int 20
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: Used : 0
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: Size : 20
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: Getting phone SMS status
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: SENDING frame type 0x00/length 0x12/18
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: 41A|54T|2B+|43C|50P|4DM|53S|3D=|22"|4DM|45E|22"|2C,|22"|4DM|45E AT+CPMS="ME","ME
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: 22"|0D                                                          ".
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: 1 "AT+CPMS="ME","ME""
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: 2 "+CPMS: "ME",0,100,"ME",0,100,"ME",0,100"
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: 3 "OK"
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: Checking line: OK
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: AT reply state: 1
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: RECEIVED frame type 0x00/length 0x43/67
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: 41A|54T|2B+|43C|50P|4DM|53S|3D=|22"|4DM|45E|22"|2C,|22"|4DM|45E AT+CPMS="ME","ME
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: 22"|0D |0D |0A |2B+|43C|50P|4DM|53S|3A:|20 |22"|4DM|45E|22"|2C, "...+CPMS: "ME",
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: 300|2C,|311|300|300|2C,|22"|4DM|45E|22"|2C,|300|2C,|311|300|300 0,100,"ME",0,100
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: 2C,|22"|4DM|45E|22"|2C,|300|2C,|311|300|300|0D |0A |0D |0A |4FO ,"ME",0,100....O
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: 4BK|0D |0A                                                      K..
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: SMS status received
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: Parsing +CPMS: "ME",0,100,"ME",0,100,"ME",0,100 with +CPMS: @i, @i, @0
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: Parsing +CPMS: "ME",0,100,"ME",0,100,"ME",0,100 with +CPMS: @s, @i, @i, @0
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: Grabbed string from reply: "ME" (parsed 4 bytes)
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: Parsed generic string "ME"
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: Generic string decoded as "ME"
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: Parsed int 0
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: Parsed int 100
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: Used : 0
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: Size : 100
Wed 2017/12/13 12:27:06 gammu-smsd[1809]: gammu: Leaving GSM_GetSMSStatus
```
Current gammu-smsdrc config:
runonincomingcall = /tmp/reject_call.sh
hangupcalls = 1

Modem used is Telit HE-910

### PR DESCRIPTION
**Pull request by kstuart**
This patch implements the concept of deferred events in order to avoid
an incoming event conflicting with a currently executing request, the
feature is currently only used for incoming calls but is a general
purpose mechanism in this regard.

Fixes #376

### CODE REVIEW

**Comment by nijel** [comment]
It seems that with this patch the debug build is often hitting it's limit on AppVeyor...

**Comment by kstuart** [comment]
Yes, I noticed, is that something we can address in future (not that familiar with AppVeyor)?

I've now a full Windows setup for testing SMSD/Gammu so will run the failing profile locally and attach results to PR, I don't expect they'll be an issue though, will update you when I've done that later today.

On 5/31/19 12:21 PM, Michal Čihař wrote:

It seems that with this patch the debug build is often hitting it's limit on AppVeyor...

**Comment by kstuart** [comment]
Oh, I see all AppVeyor builds succeeded on latest try, scratch my last message then ;)

Will you be merging this today?

**Comment by nijel** [comment]
The problem is only with the debug build. It's slow as hell because it's used to gather test coverage and that is really show right now. I do not use Windows at all, so this always was something I didn't want to touch ;-).

**Comment by nijel** [comment]
Merged, thanks for your contribution!

**Pull request merged**
