### PR TITLE
Improve smsd delivery report matching

### PR DESCRIPTION
**Pull request by tbitowt**
Fix for #319

### CODE REVIEW

**Comment by nijel** [comment]
Thanks for patch, however I'm not sure this is good approach, as it is adding quite complex logic to the SQL, the question is whether it will work with all supported SQL engines.

Maybe it would be better to do the replacement when sending the message, so that the data in the table is already using `+` instead of `00`...

**Comment by tbitowt** [comment]
Is the `CreateMessage` in `message-cmdline.c` the only place to do it? Or there are more?

**Comment by nijel** [comment]
I was originally thinking about doing that when inserting into sentitems, but maybe doing it generally is better idea. Can you test if https://github.com/gammu/gammu/pull/322 works good?

**Comment by nijel** [comment]
Closing in favor of #322

**Pull request closed without merging**
